# Generated by Django 5.1.2 on 2024-11-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_tableresto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableresto',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
